# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Clint Harvey
description: Jekyll Experimentation
email: sch@rw-dev.com
include: [_pages]


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://github.clintharvey.net" # the base hostname & protocol for your site

#sidebar
default-image: moo.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: Clint harvey
copyright:
   name: Clint Harvey
   link: 'http://clintharvey.net'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics:

#social
facebook: http://facebook.com/sharvey
twitter: http://twitter.com/scharvey
github: http://github.com/scharvey
instagram: http://instagram.com/scharvey

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]
