
title: Clint Harvey
description: Everything You Never Wanted to Know
url: http://jekyll.clintharvey.net
permalink: ':title/'

markdown: kramdown
baseurl: "//jekyll.clintharvey.net"


sass:
    style: compressed


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge


# Tracker
analytics: UA-5217991-1


# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:

include: [_pages]
version: 0.8

gems: [jekyll-paginate, jekyll-seo-tag, jekyll-twitter-plugin]
